import { LearningModule } from '../types';

export const LEARNING_MODULES: LearningModule[] = [
  {
    id: 'quiz-history',
    title: 'History Quiz',
    description: 'Test your knowledge of world history with AI-generated questions',
    icon: '🏛️',
    color: '#FF6B6B',
    gradient: ['#FF6B6B', '#FF8E53'],
    category: 'quiz',
  },
  {
    id: 'quiz-science',
    title: 'Science Quiz',
    description: 'Explore physics, chemistry, and biology through interactive quizzes',
    icon: '🔬',
    color: '#4ECDC4',
    gradient: ['#4ECDC4', '#44A08D'],
    category: 'quiz',
  },
  {
    id: 'flashcards-vocab',
    title: 'Vocabulary Builder',
    description: 'Expand your vocabulary with AI-powered flashcards',
    icon: '📚',
    color: '#A8E6CF',
    gradient: ['#A8E6CF', '#56AB2F'],
    category: 'flashcard',
  },
  {
    id: 'flashcards-concepts',
    title: 'Concept Cards',
    description: 'Master complex concepts through spaced repetition flashcards',
    icon: '🧠',
    color: '#B8B5FF',
    gradient: ['#B8B5FF', '#7C3AED'],
    category: 'flashcard',
  },
  {
    id: 'language-spanish',
    title: 'Spanish Tutor',
    description: 'Practice Spanish conversation with your AI language tutor',
    icon: '🇪🇸',
    color: '#FFD93D',
    gradient: ['#FFD93D', '#FF6B6B'],
    category: 'language',
  },
  {
    id: 'language-french',
    title: 'French Tutor',
    description: 'Learn French naturally through AI-powered conversation',
    icon: '🇫🇷',
    color: '#6BCEFF',
    gradient: ['#6BCEFF', '#3B82F6'],
    category: 'language',
  },
  {
    id: 'math-algebra',
    title: 'Algebra Practice',
    description: 'Solve algebra problems with step-by-step AI explanations',
    icon: '✏️',
    color: '#FFA07A',
    gradient: ['#FFA07A', '#FF4500'],
    category: 'math',
  },
  {
    id: 'math-calculus',
    title: 'Calculus Helper',
    description: 'Understand calculus concepts with guided problem solving',
    icon: '📐',
    color: '#98D8C8',
    gradient: ['#98D8C8', '#009473'],
    category: 'math',
  },
  {
    id: 'quiz-geography',
    title: 'Geography Quiz',
    description: 'Explore countries, capitals, and cultures around the world',
    icon: '🌍',
    color: '#C3B1E1',
    gradient: ['#C3B1E1', '#9B59B6'],
    category: 'quiz',
  },
  {
    id: 'coding-basics',
    title: 'Coding Basics',
    description: 'Learn programming fundamentals through interactive coding challenges',
    icon: '💻',
    color: '#96E6A1',
    gradient: ['#96E6A1', '#21D4FD'],
    category: 'coding',
  },
];

export const MODULE_TOPICS: Record<string, string> = {
  'quiz-history': 'World History',
  'quiz-science': 'General Science',
  'quiz-geography': 'World Geography',
  'flashcards-vocab': 'English Vocabulary',
  'flashcards-concepts': 'General Knowledge Concepts',
  'language-spanish': 'Spanish',
  'language-french': 'French',
  'math-algebra': 'Algebra',
  'math-calculus': 'Calculus',
  'coding-basics': 'Programming Basics',
};
